module.exports = {
  extends: ['@commitlint/config-conventional'],
  parserPreset: {
    parserOpts: {
      // The separator is a colon followed by whitespace. This preserves colons in Gitmoji
      // aliases such as ":memo: Docs" while capturing the last header separator.
      headerPattern: /^(?<type>.+):\s+(?<subject>.+)$/,
      headerCorrespondence: ['type', 'subject'],
    },
  },
  rules: {
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [0],
    'subject-case': [0],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        '✨ Feat',
        ':sparkles: Feat',
        '📦 Chore',
        '📦️ Chore',
        ':package: Chore',
        '💄 Design',
        ':lipstick: Design',
        '🐛 Fix',
        ':bug: Fix',
        '🎨 Style',
        ':art: Style',
        '⚡ Perf',
        ':zap: Perf',
        '🔥 Remove',
        ':fire: Remove',
        '🚀 Release',
        ':rocket: Release',
        '🎉 Init',
        ':tada: Init',
        '✅ Test',
        ':white_check_mark: Test',
        '🔒 Security',
        ':lock: Security',
        '🔐 Security',
        ':closed_lock_with_key: Security',
        '🚨 Fix',
        ':rotating_light: Fix',
        '♻ Refactor',
        '♻️ Refactor',
        ':recycle: Refactor',
        '🔨 Refactor',
        ':hammer: Refactor',
        '🔨 Modify',
        ':hammer: Modify',
        '🚚 Rename',
        ':truck: Rename',
        '📝 Docs',
        ':memo: Docs',
        '➖ Remove',
        ':heavy_minus_sign: Remove',
        '🔖 Release',
        ':bookmark: Release',
        '🧪 Test',
        ':test_tube: Test',
        '🚑 Hotfix',
        '🚑️ Hotfix',
        ':ambulance: Hotfix',
      ],
    ],
  },
}
